tools : ["bwa-pre", "seqbuster", "razers3-pre", "STAR", "ShortStack", "GSNAP", "BWAa", "Bowtie1", "Bowtie2", "Manatee"]
tools_features : ["STAR", "ShortStack", "GSNAP", "BWAa", "Bowtie1", "Bowtie2"]
norazers3: 0
noseqbusterfull: 1
noquant: 0
round: "S3"
