tools : ["bwa-pre", "seqbuster", "razers3-pre", "ShortStack", "GSNAP", "BWAa", "Bowtie1", "Bowtie2", "STAR", "Manatee"] #missing STAR
tools_features : ["ShortStack", "GSNAP", "BWAa", "Bowtie1", "Bowtie2", "STAR"] #missing STAR
tools_quant: ["bwa-pre", "razers3-pre"]
norazers3: 0
noseqbusterfull: 0
noquant: 0
round: "S0"
